apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - github.com/phillebaba/manifests//chaoskube/base
images:
  - name: quay.io/linki/chaoskube
    newTag: v0.15.1-arm32v6
namespace: monitoring
