apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - github.com/phillebaba/manifests//kube-monkey/base?ref=feature/kube-monkey-configmap
configMapGenerator:
  - name: kube-monkey-config-map
    behavior: replace
    files:
      - config.toml
images:
  - name: ayushsobti/kube-monkey
    newName: phillebaba/kube-monkey
    newTag: v0.3.0
namespace: kube-system
