apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- github.com/phillebaba/manifests//traefik/base

namespace: ingress

configMapGenerator:
- name: traefik-conf
  files:
  - traefik.toml

patchesStrategicMerge:
- patch_deployment.yml
- patch_service.yml
