apiVersion: v1
kind: Service
metadata:
  name: traefik
spec:
  ports:
  - port: 80
    protocol: TCP
  - port: 443
    protocol: TCP
  - port: 8000
    protocol: TCP
  - port: 4443
    protocol: TCP
  type: LoadBalancer
