apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- github.com/phillebaba/sensor-demo//manifests
resources:
- ingress_route.yml
patchesStrategicMerge:
- deployment_patch.yml
namePrefix: sensor-demo-
namespace: application
