apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- github.com/phillebaba/sensor-demo//manifests?ref=95005ccb4736f9bc473c67f1664c2d0c20515cd7
resources:
- ingress_route.yml
patchesStrategicMerge:
- deployment_patch.yml
namePrefix: sensor-demo-
namespace: application
