apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- github.com/phillebaba/sensor-demo//manifests
resources:
- ingress_route.yml
patchesStrategicMerge:
- deployment_patch.yml
namePrefix: sensor-demo-
namespace: application

images:
- name: phillebaba/sensor-demo-web
  newTag: 8edb441
- name: phillebaba/sensor-demo
  newTag: 8edb441
