apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: kube-ops-view
spec:
  entryPoints:
    - http
  routes:
  - match: Host(`kube-ops-view.lainecloud.com`) && PathPrefix(`/notls`)
    kind: Rule
    services:
    - name: kube-ops-view
      port: 80

