apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - github.com/phillebaba/manifests//kube-ops-view/base
images:
  - name: hjacobs/kube-ops-view
    newName: phillebaba/kube-ops-view
    newTag: latest
patchesJson6902:
  - target:
      group: extensions
      version: v1beta1
      kind: Ingress
      name: kube-ops-view
    path: ingress_patch.yml
namespace: monitoring
