apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- github.com/phillebaba/manifests//kube-ops-view/base
resources:
- ingress_route.yml
images:
  - name: hjacobs/kube-ops-view
    newName: phillebaba/kube-ops-view
    newTag: latest
namespace: monitoring
