apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - github.com/phillebaba/manifests//bike-touring-tracker/overlays/postgres
patchesStrategicMerge:
  - patch.yml
namespace: application
