apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: btt
  annotations:
    kubernetes.io/ingress.class: "traefik-private"
spec:
  rules:
  - host: btt.internal.lainecloud.com
    http:
      paths:
      - backend:
          serviceName: btt
          servicePort: 80
        path: /
