defaultEntryPoints = ["http","https"]
debug = false
logLevel = "INFO"

InsecureSkipVerify = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[api]
  entryPoint = "traefik"
  dashboard = true

[metrics]
  [metrics.prometheus]
    buckets = [0.1,0.3,1.2,5.0]

[kubernetes]
  ingressClass = "traefik-public"

[acme]
  email = "philip.laine@gmail.com"
  storage = "acme.json"
  acmeLogging = true
  entryPoint = "https"
  OnHostRule = true
  caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
  [acme.httpChallenge]
    entryPoint="http"
