apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- github.com/phillebaba/manifests//node-feature-discovery/base

namespace: platform

images:
- name: quay.io/kubernetes_incubator/node-feature-discovery
  newName: phillebaba/node-feature-discovery-usb
  newTag: 3ea8c94

patchesStrategicMerge:
- daemonset_patch.yml
