apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- github.com/phillebaba/manifests//traefik/base?ref=5e5e9b9ca4dca62bf41ac5f5b3a3599cb39f8e14

nameSuffix: -private

#configMapGenerator:
#  - name: traefik-conf
#    behavior: replace
#    files:
#      - traefik.toml

#patchesStrategicMerge:
#  - increase_replicas.yml
