apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: traefik
spec:
  replicas: 1
  template:
    spec:
      volumes:
      - name: config
        configMap:
          name: traefik-conf
      containers:
      - name: traefik
        volumeMounts:
        - mountPath: "/config"
          name: "config"
        args:
        - --configfile=/config/traefik.toml
